# https://taskfile.dev

version: '3'

tasks:
  dev:
    desc: 👨🏻‍💻 run git-tools in «dev» mode
    cmds:
      - cargo watch -c -x "run --"

  build:watch:
    desc: ⚡ watch git-tools «build»
    cmds:
      - cargo watch -c -x "build"

  build:check:
    desc: ⚡ build ids «release» and check the size
    cmds:
      - cargo build --release
      - python check_size.py

  fmt:
    desc: 🎨 format git-tools
    cmds:
      - cargo +nightly fmt --all
  
  fmt:check:
    desc: 🎨 check git-tools formatting
    cmds:
      - cargo +nightly fmt --all --check

  lint:
    desc: 🧶 lint git-tools
    cmds:
      - cargo clippy --fix --workspace --allow-staged
  
  lint:check:
    desc: 🧶 check git-tools linting
    cmds:
      - cargo clippy --workspace

  fmt+lint:
    desc: 🎨🧶 format and lint git-tools
    cmds:
      - task fmt
      - git add .
      - task lint

  release:patch:
    desc: 🚀 release git-tools
    cmds:
      - cargo release patch --execute --no-confirm --package git-tools

  release:minor:
    desc: 🚀 release git-tools
    cmds:
      - cargo release minor --execute --no-confirm --package git-tools

  release:major:
    desc: 🚀 release git-tools
    cmds:
      - cargo release major --execute --no-confirm --package git-tools

