[package]
name = "sync"
version = "0.1.0"
readme.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
common = { path = "../../common" }
eyre = { workspace = true }
lool = { workspace = true }